#!/usr/bin/env python3
"""
End-to-end smoke test against a RUNNING stack (GPU). Run it after any model or
dependency change, before anyone listens to the result.

    STACK_TOKEN=... python3 tools/smoke.py                  # ws://127.0.0.1:8790
    python3 tools/smoke.py --url ws://127.0.0.1:8790 --quick
    python3 tools/smoke.py --langs es,km                    # only those cases
    python3 tools/smoke.py --edition commercial             # a stack run with EDITION=commercial
    python3 tools/smoke.py --edition commercial --load 8 --load-langs ko,ru,tr,ar,vi,sw,id,km
                                                            # VoxCPM2 capacity: 8 listeners at once

On a pod, tunnel first:  ssh -L 8790:127.0.0.1:8790 root@<ip> -p <port>

Cases (each streams a clip at real-time pace, as the apps do):

  en -> es ja km lo tl sw fa ht ro   every voice engine (Kokoro, VoxCPM2, Piper,
                                     MMS or Coqui) and both translators (Hy-MT2,
                                     MADLAD), src=auto
  km -> en                           Omnilingual recognition
  concurrency                        four connections at once, three rounds; each
                                     must hear the WHOLE sentence (the shared-VAD
                                     regression lost the first words)
  pair                               Lithos Talk: route=to&cands=en,ro, both
                                     directions on the same audio; ro translates,
                                     en skips the English
  auth                               a bad token is refused (4401)
  --load N (only this, when given)   N connections at once, en -> the --load-langs
                                     round-robin (VoxCPM2 languages), each streaming
                                     the clip: every one must hear the translation
                                     spoken (VoxCPM2, or the next voice when VoxCPM2
                                     is at capacity) with first audio under
                                     --load-max-first s. Prints first audio and voice
                                     seconds per connection; which voice spoke is in
                                     the server log ("VoxCPM2 busy", "VoxCPM2 stats").

Each case checks: the heard transcript contains the expected words (fuzzy), a
translation came back, over 0.5 s of voice audio, no error message. Prints a
table, then ALL PASSED or the failures; exits 1 on any failure.

--edition (default: $EDITION, else nonprofit) must match the running stack.
Which languages that edition serves as TEXT ONLY (or eSpeak NG only) comes from
server/stack_config.py (the same apply_edition() the server enforces): for
those, the case passes only with a translation and NO audio. Commercial also
runs en -> every language whose voice differs from nonprofit (ko tr ru ar id
vi de fr ...), so each replacement voice is heard at least once.

The clips are tests/audio/en.wav and km.wav (see tests/audio/README.md). Needs
`pip install websockets`. The token is read from --token or $STACK_TOKEN and
never printed.
"""
import argparse
import asyncio
import difflib
import json
import os
import re
import sys
import time
import unicodedata
import wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO = os.path.join(ROOT, "tests", "audio")
RATE = 24000
FRAME = RATE // 10 * 2  # 100 ms of PCM16

# What each clip says (tests/audio/README.md).
CLIPS = {
    # ~25 s of Spanish with no pause long enough to end an utterance: forces the
    # room's sentence cut (Kokoro ef_dora, generated by the stack; see README).
    "es_long": ("es_long.wav", "La reunión empezará a las diez de la mañana en el salón principal. "
                "Después de la oración, el obispo leerá los anuncios de la semana. "
                "Los jóvenes se reunirán en la sala de clases para preparar la actividad del sábado. "
                "Si alguien necesita transporte, puede hablar con el hermano García al final de la reunión. "
                "Gracias por venir y que tengan una buena semana."),
    "en": ("en.wav", "Could you tell me where the train station is?"),
    "km": ("km.wav", "កុំបារម្ភអី បន្តិចទៀតប្រហែលម្ភៃនាទីគ្រូពេទ្យនឹងជួបហើយ។"),
}

# en -> X. Together they cover every voice engine and both translators (see
# languages.toml): es Kokoro/Hy-MT2, ja Kokoro/Hy-MT2, km VoxCPM2/Hy-MT2,
# lo VoxCPM2/MADLAD, tl VoxCPM2/Hy-MT2, sw Piper/MADLAD, fa Piper/Hy-MT2,
# ht MMS or Coqui/MADLAD, ro Piper/MADLAD.
TARGETS = ["es", "ja", "km", "lo", "tl", "sw", "fa", "ht", "ro"]
QUICK_TARGETS = ["es", "km", "sw", "ht"]

# A translation into a non-Latin language must be in its script.
SCRIPTS = {
    "ja": r"[぀-ヿ一-鿿]", "km": r"[ក-៿]", "lo": r"[຀-໿]",
    "fa": r"[؀-ۿ]", "zh": r"[一-鿿]", "ko": r"[가-힯]",
    "ar": r"[؀-ۿ]", "ru": r"[Ѐ-ӿ]", "uk": r"[Ѐ-ӿ]",
    "hi": r"[ऀ-ॿ]", "bn": r"[ঀ-৿]", "ur": r"[؀-ۿ]",
}


def edition_plan(edition):
    """(text-only languages, languages whose voice chain differs from
    nonprofit) for an edition, from stack_config: what the server enforces."""
    sys.path.insert(0, os.path.join(ROOT, "server"))
    import stack_config
    table, _ = stack_config.load()
    reviews = stack_config.load_reviews()
    _, rep = stack_config.apply_edition(table, edition, reviews)
    _, base = stack_config.apply_edition(table, "nonprofit", reviews)
    text_only = {l for l, r in rep.items() if r["text_only"]}
    changed = [l for l in table if [(n, v) for n, v, _ in rep[l]["voices"]]
               != [(n, v) for n, v, _ in base[l]["voices"]]]
    return text_only, changed


def read_clip(src):
    name, text = CLIPS[src]
    with wave.open(os.path.join(AUDIO, name)) as w:
        if w.getframerate() != RATE or w.getnchannels() != 1 or w.getsampwidth() != 2:
            sys.exit(f"{name}: need {RATE} Hz mono PCM16")
        return w.readframes(w.getnframes()), text


def _norm(s):
    """Lowercase; punctuation and symbols become spaces. Letters, digits and
    combining marks stay (Khmer vowel signs are marks, which \\w would drop)."""
    s = unicodedata.normalize("NFC", s).lower()
    return "".join(c if unicodedata.category(c)[0] in "LMN" else " " for c in s)


def heard_ok(heard, want):
    """Fuzzy: most of the expected words, starting with the first two (a lost
    opening is exactly the regression the concurrency case is for). Scripts
    without spaces (Khmer) compare characters instead."""
    h, w = _norm(heard), _norm(want)
    words = w.split()
    if len(words) >= 4 and len(w.replace(" ", "")) / len(words) < 12:  # a spaced script
        hw = h.split()
        found = sum(1 for x in words if any(difflib.SequenceMatcher(None, x, y).ratio() >= 0.8 for y in hw))
        head = all(any(difflib.SequenceMatcher(None, x, y).ratio() >= 0.8 for y in hw[:4]) for x in words[:2])
        return found / len(words) >= 0.75 and head
    a, b = h.replace(" ", ""), w.replace(" ", "")
    return difflib.SequenceMatcher(None, a, b).ratio() >= 0.6


def connect(url, token):
    import websockets
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    try:  # websockets >= 14
        return websockets.connect(url, additional_headers=headers, max_size=2 ** 24, open_timeout=20)
    except TypeError:
        return websockets.connect(url, extra_headers=headers, max_size=2 ** 24, open_timeout=20)


async def run_one(base, token, query, src, timeout=30.0, expect_output=True, quiet_s=3.0, expect_audio=True):
    """Stream one clip through one connection; gather what came back."""
    pcm, _ = read_clip(src)
    r = {"route": [], "heard": "", "heard_parts": [], "said": "", "voice_s": 0.0, "first_audio_s": None,
         "errors": [], "close": None, "frames": 0, "max_frame": 0}
    rate = RATE
    try:
        async with connect(f"{base}/translate?{query}", token) as ws:
            hello = json.loads(await asyncio.wait_for(ws.recv(), 20))
            if hello.get("type") != "hello":
                r["errors"].append(f"expected hello, got {hello.get('type')}")
                return r
            rate = int(hello.get("rate", RATE))
            state = {"end": None, "last_audio": None, "last_text": None}

            async def send():
                # 0.5 s of room tone first, the clip at real time, then silence
                # until the receiver is done (a live mic never stops sending).
                await ws.send(b"\x00" * FRAME * 5)
                await asyncio.sleep(0.5)
                for i in range(0, len(pcm), FRAME):
                    await ws.send(pcm[i:i + FRAME])
                    await asyncio.sleep(0.1)
                state["end"] = time.perf_counter()
                while True:
                    await ws.send(b"\x00" * FRAME)
                    await asyncio.sleep(0.1)

            async def receive():
                async for m in ws:
                    now = time.perf_counter()
                    if isinstance(m, bytes):
                        r["frames"] += 1
                        r["max_frame"] = max(r["max_frame"], len(m))
                        r["voice_s"] += len(m) / 2 / rate
                        state["last_audio"] = now
                        if r["first_audio_s"] is None and state["end"]:
                            r["first_audio_s"] = now - state["end"]
                        continue
                    d = json.loads(m)
                    t = d.get("type")
                    if t == "route":
                        r["route"].append(d.get("src"))
                    elif t == "inputTranscript":
                        r["heard"] += d.get("text", "")
                        r["heard_parts"].append(d.get("text", ""))
                    elif t == "transcript":
                        r["said"] += d.get("delta", "")
                        state["last_text"] = now
                    elif t == "error":
                        r["errors"].append(d.get("detail", "error"))

            async def settle():
                # Done when audio has stopped for quiet_s after a translation, or
                # (nothing expected) 8 s after the clip ended, or at the timeout.
                t0 = time.perf_counter()
                while time.perf_counter() - t0 < timeout:
                    await asyncio.sleep(0.2)
                    now = time.perf_counter()
                    if state["end"] is None:
                        continue
                    if expect_output and r["said"] and state["last_audio"] and now - state["last_audio"] > quiet_s:
                        return
                    # A text-only language: the translation, then a few seconds to
                    # be sure no audio follows it.
                    if (expect_output and not expect_audio and r["said"] and state["last_text"]
                            and now - state["last_text"] > max(quiet_s, 5.0)):
                        return
                    if not expect_output and now - state["end"] > 8:
                        return

            tasks = [asyncio.create_task(send()), asyncio.create_task(receive())]
            await settle()
            if tasks[1].done() and tasks[1].exception() is None:
                r["errors"].append(f"server closed the connection ({ws.close_code})")
            for t in tasks:
                t.cancel()
            await asyncio.gather(*tasks, return_exceptions=True)
    except Exception as e:  # noqa: BLE001 - reported, never raised
        code = getattr(getattr(e, "rcvd", None), "code", None)
        r["close"] = code
        r["errors"].append(f"{type(e).__name__}{f' {code}' if code else ''}")
    return r


def check(r, want_heard, lang, voice=True):
    fails = []
    if r["errors"]:
        fails.append("; ".join(r["errors"]))
    if want_heard and not heard_ok(r["heard"], want_heard):
        fails.append(f"heard {r['heard']!r}")
    if not r["said"].strip():
        fails.append("no translation")
    elif lang in SCRIPTS and not re.search(SCRIPTS[lang], r["said"]):
        fails.append(f"translation not in {lang} script")
    if voice and r["voice_s"] <= 0.5:
        fails.append(f"voice {r['voice_s']:.1f}s")
    if not voice and r["voice_s"] > 0:
        fails.append(f"TEXT ONLY expected, got {r['voice_s']:.1f}s of audio")
    return fails


async def auth_case(base):
    """A bad token must be refused with 4401."""
    import websockets
    try:
        async with connect(f"{base}/translate?lang=es&src=auto", "not-a-valid-token") as ws:
            try:
                msg = await asyncio.wait_for(ws.recv(), 10)
                return [f"bad token accepted (got {str(msg)[:40]!r}); is the server open (no STACK_TOKEN)?"]
            except websockets.ConnectionClosed as e:
                code = e.rcvd.code if e.rcvd else None
                return [] if code == 4401 else [f"closed with {code}, want 4401"]
    except websockets.ConnectionClosed as e:
        code = e.rcvd.code if e.rcvd else None
        return [] if code == 4401 else [f"closed with {code}, want 4401"]
    except Exception as e:  # noqa: BLE001
        return [f"{type(e).__name__}"]


def row(case, r, fails):
    first = f"{r['first_audio_s']:.2f}s" if r and r.get("first_audio_s") is not None else "-"
    heard = (r or {}).get("heard", "").strip().replace("\n", " ")
    said = (r or {}).get("said", "").strip().replace("\n", " ")
    voice = f"{r['voice_s']:.1f}s" if r else "-"
    return (case, heard, said, voice, first, "ok" if not fails else "FAIL: " + "; ".join(fails))


def clip(s, n):
    return s if len(s) <= n else s[:n - 1] + "…"


def print_table(rows):
    print()
    print(f"{'case':22} {'heard':34} {'translation':34} {'voice':>6} {'1st audio':>9}  result")
    print("-" * 125)
    for case, heard, said, voice, first, res in rows:
        print(f"{clip(case, 22):22} {clip(heard, 34):34} {clip(said, 34):34} {voice:>6} {first:>9}  {res}")
    print("-" * 125)


async def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--url", default="ws://127.0.0.1:8790", help="the stack, without /translate")
    ap.add_argument("--token", default=None, help="access token (default: $STACK_TOKEN); never printed")
    ap.add_argument("--langs", default=None,
                    help="only these cases, e.g. es,km (target languages; km also selects km->en, "
                         "ro the Talk pair, en the concurrency case)")
    ap.add_argument("--quick", action="store_true",
                    help="fewer languages (es km sw ht), one concurrency round")
    ap.add_argument("--timeout", type=float, default=40.0, help="seconds per connection")
    ap.add_argument("--edition", default=os.environ.get("EDITION") or "nonprofit",
                    choices=("nonprofit", "commercial"),
                    help="the running stack's EDITION: text-only languages must then come back without audio")
    ap.add_argument("--load", type=int, default=0, metavar="N",
                    help="instead of the cases: N simultaneous connections into --load-langs (VoxCPM2 capacity)")
    ap.add_argument("--load-langs", default="ko,ru,tr,ar,vi,sw,id,km",
                    help="target languages for --load, assigned round-robin")
    ap.add_argument("--load-clip", default="en", choices=sorted(CLIPS),
                    help="what each --load connection streams (es_long: ~25 s, five sentences)")
    ap.add_argument("--load-rounds", type=int, default=1, help="--load this many times, one after another")
    ap.add_argument("--load-max-first", type=float, default=4.0,
                    help="--load fails a connection whose first audio comes later than this (s after the clip)")
    args = ap.parse_args()
    if args.load:
        return await load_test(args)
    text_only, changed = edition_plan(args.edition)
    speaks = lambda lang: lang not in text_only  # noqa: E731
    token = args.token if args.token is not None else os.environ.get("STACK_TOKEN", "")
    base = args.url.rstrip("/")
    if base.endswith("/translate"):
        base = base[: -len("/translate")]
    only = {x.strip() for x in args.langs.split(",") if x.strip()} if args.langs else None
    want = lambda k: only is None or k in only  # noqa: E731

    en_text = CLIPS["en"][1]
    rows, failed = [], []

    def record(case, r, fails):
        rows.append(row(case, r, fails))
        if fails:
            failed.append(case)
        print(f"  {case}: {'ok' if not fails else 'FAIL ' + '; '.join(fails)}", flush=True)

    print(f"smoke test against {base} ({'token set' if token else 'NO TOKEN'}), edition {args.edition}; "
          f"text only: {', '.join(sorted(text_only)) or 'none'}", flush=True)

    targets = list(QUICK_TARGETS if args.quick else TARGETS)
    if args.edition != "nonprofit" and not args.quick:
        targets += [l for l in changed if l not in targets and l != "en"]
    for lang in targets:
        if not want(lang):
            continue
        r = await run_one(base, token, f"lang={lang}&src=auto", "en", args.timeout, expect_audio=speaks(lang))
        fails = check(r, en_text, lang, voice=speaks(lang))
        if not r["route"]:
            fails.append("no language detected (is language ID loaded?)")
        elif r["route"][0] != "en":
            fails.append(f"detected {r['route'][0]}, not en")
        record(f"en->{lang}", r, fails)

    if want("km"):
        r = await run_one(base, token, "lang=km&src=auto", "km", args.timeout)
        fails = check(r, CLIPS["km"][1], "en")
        if not r["route"]:
            fails.append("no language detected (is language ID loaded?)")
        elif r["route"][0] != "km":
            fails.append(f"detected {r['route'][0]}, not km")
        record("km->en (omni)", r, fails)

    if want("en"):
        # The per-connection VAD regression (docs/dev/lessons-learned.md): with one
        # shared Silero, four callers at once lost their first words.
        rounds = 1 if args.quick else 3
        qs = ["lang=es&src=auto", "lang=fr&src=auto", "lang=ro&src=auto", "lang=ja&src=auto"]
        for n in range(1, rounds + 1):
            rs = await asyncio.gather(*[run_one(base, token, q, "en", args.timeout,
                                                expect_audio=speaks(q.split("&")[0][5:])) for q in qs])
            for q, r in zip(qs, rs):
                lang = q.split("&")[0][5:]
                record(f"concurrent {n} en->{lang}", r, check(r, en_text, lang, voice=speaks(lang)))

    if want("ro"):
        # Lithos Talk: one connection per direction on the same microphone.
        a, b = await asyncio.gather(
            run_one(base, token, "lang=ro&src=auto&route=to&cands=en,ro", "en", args.timeout,
                    expect_audio=speaks("ro")),
            run_one(base, token, "lang=en&src=auto&route=to&cands=en,ro", "en", args.timeout,
                    expect_output=False))
        record("pair to=ro", a, check(a, en_text, "ro", voice=speaks("ro")))
        fails = list(b["errors"])
        if b["route"][:1] != ["en"]:
            fails.append(f"route {b['route']}, want en")
        if b["said"] or b["heard"] or b["voice_s"]:
            fails.append("translated its own language (should skip)")
        record("pair to=en (skips)", b, fails)

    if want("long"):
        # A long reading with no pause, into a ROOM (Live Translation): past the
        # max utterance the stack must cut after a sentence end, in the speaker's
        # language. Regression: the cut decoded Spanish as English and fell back
        # to the quietest point, mid-sentence (docs/dev/lessons-learned.md).
        r = await run_one(base, token, f"lang=en&src=auto&room=smoke-long-{os.getpid()}", "es_long",
                          max(args.timeout, 90), quiet_s=12.0)
        parts = [p.strip() for p in r["heard_parts"] if p.strip()]
        fails = check(r, CLIPS["es_long"][1], "en")
        if not r["route"]:
            fails.append("no language detected (is language ID loaded?)")
        elif r["route"][0] != "es":
            fails.append(f"detected {r['route'][0]}, not es")
        if len(parts) < 2:
            fails.append(f"{len(parts)} utterance(s): no forced cut happened")
        mid = [p for p in parts[:-1] if p[-1] not in ".?!…"]
        if mid:
            fails.append(f"cut mid-sentence after {mid[0][-40:]!r}")
        print("    utterances: " + " | ".join(parts), flush=True)
        record("long es reading (room)", r, fails)

    fails = await auth_case(base)
    record("auth bad token", None, fails)

    print_table(rows)
    if failed:
        print(f"FAILED ({len(failed)}): {', '.join(failed)}")
        return 1
    print("ALL PASSED")
    return 0


async def load_test(args):
    """--load: N listeners at once in VoxCPM2 languages. Time to first audio
    (after the clip ends) and voice seconds per connection; all must speak."""
    token = args.token if args.token is not None else os.environ.get("STACK_TOKEN", "")
    base = args.url.rstrip("/").removesuffix("/translate")
    langs = [x.strip() for x in args.load_langs.split(",") if x.strip()]
    want = CLIPS[args.load_clip][1]
    tgt = [langs[i % len(langs)] for i in range(args.load)]
    print(f"load test against {base}: {args.load} connections at once ({','.join(tgt)}), clip {args.load_clip}, "
          f"{args.load_rounds} round(s)", flush=True)
    rows, failed, firsts, total_voice = [], [], [], 0.0
    t_all = time.perf_counter()
    for n in range(1, args.load_rounds + 1):
        rs = await asyncio.gather(*[run_one(base, token, f"lang={lg}&src=auto", args.load_clip,
                                            max(args.timeout, 90 if args.load_clip == "es_long" else 40),
                                            quiet_s=6.0 if args.load_clip == "es_long" else 3.0)
                                    for lg in tgt])
        for i, (lg, r) in enumerate(zip(tgt, rs)):
            fails = check(r, want, lg)
            if r["first_audio_s"] is not None and r["first_audio_s"] > args.load_max_first:
                fails.append(f"first audio {r['first_audio_s']:.1f}s > {args.load_max_first:.1f}s")
            case = f"load {n}.{i + 1} en->{lg}"
            rows.append(row(case, r, fails))
            if fails:
                failed.append(case)
            if r["first_audio_s"] is not None:
                firsts.append(r["first_audio_s"])
            total_voice += r["voice_s"]
    print_table(rows)
    if firsts:
        firsts.sort()
        print(f"first audio after the clip: median {firsts[len(firsts) // 2]:.2f}s, max {firsts[-1]:.2f}s "
              f"(n={len(firsts)}); voice {total_voice:.1f}s in total; wall {time.perf_counter() - t_all:.1f}s")
    if failed:
        print(f"FAILED ({len(failed)}): {', '.join(failed)}")
        return 1
    print("ALL PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
