#!/usr/bin/env python3
"""Make and choose the fixed reference voice a VoxCPM2 (or Chatterbox) language
speaks in, voices/voxcpm/<lang>.wav: candidates generated by VoxCPM2 itself (so
synthetic speakers, Apache 2.0, no third-party voice), each cloned on a few
sentences and scored. Three steps, each in the environment that has its model
(GPU pod):

    # 1. candidates + clones, in VoxCPM2's venv
    /workspace/venv_voxcpm/bin/python tools/voice_refs.py gen --out /opt/refs --langs ko,tr
    # 2. optional: the same sentences through Chatterbox Multilingual (a venv with
    #    chatterbox-tts 0.1.7 installed --no-deps over torch 2.8), cloned from each candidate
    /opt/venv_chatterbox/bin/python tools/voice_refs.py chatterbox --out /opt/refs --langs ko,tr
    # 3. scores, in the stack's Python (faster-whisper): CER of every clip, pitch per clip
    python3 tools/voice_refs.py score --out /opt/refs

Per candidate: A and B are designed voices (VoxCPM2's "(description)text"
voice design: a calm adult woman, a calm adult man), C and D are random
speakers. A candidate is STABLE when every clone's median pitch stays within
25% of the reference's and on the same side of 165 Hz: the Lao lesson (a new
speaker, even a man turning into a woman, mid-phrase; docs/dev/lessons-learned.md
§5). `score` picks, per language, the stable candidate with the lowest mean
clone character error rate (Whisper large-v3). A person listens before it ships.
"""
import argparse
import json
import os
import sys
import time
import unicodedata
import wave

# A reference sentence (what the candidate speaker says) and three test
# sentences per language, the kind of thing the stack voices.
SENTENCES = {
    "ko": ("안녕하세요. 오늘 모임에 와 주셔서 진심으로 감사합니다. 잠시 후에 시작하겠습니다.",
           ["기차역이 어디에 있는지 알려 주실 수 있나요?", "회의는 오전 열 시에 본당에서 시작됩니다.",
            "도움이 필요하시면 언제든지 말씀해 주세요."]),
    "tr": ("Merhaba. Bugün buraya geldiğiniz için hepinize çok teşekkür ederiz. Toplantı birazdan başlayacak.",
           ["Tren istasyonunun nerede olduğunu söyleyebilir misiniz?",
            "Toplantı sabah saat onda ana salonda başlayacak.", "Yardıma ihtiyacınız olursa lütfen bize haber verin."]),
    "ru": ("Здравствуйте. Спасибо всем, что пришли сегодня. Собрание скоро начнётся.",
           ["Не подскажете, где находится железнодорожный вокзал?",
            "Собрание начнётся в десять часов утра в главном зале.", "Если вам нужна помощь, пожалуйста, скажите нам."]),
    "ar": ("مرحبا بكم. شكرا لكم جميعا على حضوركم اليوم. سيبدأ الاجتماع بعد قليل.",
           ["هل يمكنك أن تخبرني أين تقع محطة القطار؟", "سيبدأ الاجتماع في الساعة العاشرة صباحا في القاعة الرئيسية.",
            "إذا كنت بحاجة إلى مساعدة، فأخبرنا من فضلك."]),
    "id": ("Selamat datang. Terima kasih kepada Anda semua yang telah hadir hari ini. Pertemuan akan segera dimulai.",
           ["Bisakah Anda memberi tahu saya di mana stasiun kereta api?",
            "Pertemuan akan dimulai pukul sepuluh pagi di aula utama.",
            "Jika Anda membutuhkan bantuan, silakan beri tahu kami."]),
    "sw": ("Karibuni. Asanteni nyote kwa kuja leo. Mkutano utaanza baada ya muda mfupi.",
           ["Unaweza kuniambia kituo cha treni kiko wapi?", "Mkutano utaanza saa nne asubuhi katika ukumbi mkuu.",
            "Kama unahitaji msaada, tafadhali tuambie."]),
    "vi": ("Xin chào quý vị. Cảm ơn tất cả mọi người đã đến hôm nay. Buổi họp sẽ bắt đầu trong giây lát.",
           ["Bạn có thể cho tôi biết ga tàu ở đâu không?", "Buổi họp sẽ bắt đầu lúc mười giờ sáng tại hội trường chính.",
            "Nếu bạn cần giúp đỡ, xin vui lòng cho chúng tôi biết."]),
}
DESIGNS = {"A": "(A calm, clear adult woman speaking at a moderate pace)",
           "B": "(A calm, clear adult man speaking at a moderate pace)", "C": "", "D": ""}


def write_wav(path, pcm, rate):
    import numpy as np
    x = np.asarray(pcm, dtype=np.float32)
    peak = float(np.abs(x).max()) if x.size else 0.0
    if peak > 1e-4:
        x = x * min(0.891 / peak, 4.0)
    with wave.open(path, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(rate)
        w.writeframes((np.clip(x, -1, 1) * 32767).astype("<i2").tobytes())


def read_wav(path):
    import numpy as np
    with wave.open(path) as w:
        rate = w.getframerate()
        x = np.frombuffer(w.readframes(w.getnframes()), "<i2").astype(np.float32) / 32768
    return x, rate


def _meta(out):
    p = os.path.join(out, "meta.json")
    return json.load(open(p)) if os.path.exists(p) else {}


def _save_meta(out, meta):
    json.dump(meta, open(os.path.join(out, "meta.json"), "w"), ensure_ascii=False, indent=1)


def gen(args):
    """VoxCPM2: four candidate speakers per language, each cloned on the test sentences."""
    from huggingface_hub import snapshot_download
    from voxcpm import VoxCPM
    path = snapshot_download(args.repo, revision=args.revision) if args.revision else args.repo
    model = VoxCPM.from_pretrained(path, load_denoiser=False)
    rate = int(model.tts_model.sample_rate)
    model.generate(text="Hello.", cfg_value=2.0, inference_timesteps=10)
    meta = _meta(args.out)
    for lang in args.langs:
        ref_text, tests = SENTENCES[lang]
        d = os.path.join(args.out, lang)
        os.makedirs(d, exist_ok=True)
        for cand, design in DESIGNS.items():
            ref = os.path.join(d, f"cand_{cand}.wav")
            t = time.time()
            wav = model.generate(text=design + ref_text, cfg_value=2.0, inference_timesteps=10)
            write_wav(ref, wav, rate)
            meta[f"{lang}/cand_{cand}.wav"] = {"text": ref_text, "engine": "voxcpm", "gen_s": time.time() - t,
                                              "audio_s": len(wav) / rate}
            for i, s in enumerate(tests, 1):
                t = time.time()
                wav = model.generate(text=s, cfg_value=2.0, inference_timesteps=10, reference_wav_path=ref)
                write_wav(os.path.join(d, f"vox_{cand}_s{i}.wav"), wav, rate)
                meta[f"{lang}/vox_{cand}_s{i}.wav"] = {"text": s, "engine": "voxcpm", "cand": cand,
                                                     "gen_s": time.time() - t, "audio_s": len(wav) / rate}
            print(f"{lang} {cand} done", flush=True)
            _save_meta(args.out, meta)


def chatterbox(args):
    """Chatterbox Multilingual on the same sentences, cloned from each candidate."""
    import torch
    from huggingface_hub import snapshot_download
    from chatterbox.mtl_tts import ChatterboxMultilingualTTS
    files = ["ve.pt", "t3_mtl23ls_v2.safetensors", "s3gen.pt", "grapheme_mtl_merged_expanded_v1.json", "conds.pt",
             "Cangjie5_TC.json"]
    t0 = time.time()
    model = ChatterboxMultilingualTTS.from_local(
        snapshot_download("ResembleAI/chatterbox", revision=args.cb_revision, allow_patterns=files), "cuda")
    load_s = time.time() - t0
    model.generate("Hello.", language_id="en")
    meta = _meta(args.out)
    for lang in args.langs:
        _, tests = SENTENCES[lang]
        d = os.path.join(args.out, lang)
        for cand in DESIGNS:
            ref = os.path.join(d, f"cand_{cand}.wav")
            if not os.path.exists(ref):
                continue
            model.prepare_conditionals(ref, exaggeration=0.5)
            for i, s in enumerate(tests, 1):
                torch.cuda.synchronize()
                t = time.time()
                wav = model.generate(s, language_id=lang, exaggeration=0.5, cfg_weight=0.5, temperature=0.8)
                torch.cuda.synchronize()
                x = wav.squeeze(0).cpu().numpy()
                write_wav(os.path.join(d, f"cb_{cand}_s{i}.wav"), x, model.sr)
                meta[f"{lang}/cb_{cand}_s{i}.wav"] = {"text": s, "engine": "chatterbox", "cand": cand,
                                                    "gen_s": time.time() - t, "audio_s": len(x) / model.sr}
            print(f"{lang} {cand} chatterbox done", flush=True)
    meta["_chatterbox"] = {"load_s": load_s, "peak_gb": torch.cuda.max_memory_allocated() / 1e9}
    _save_meta(args.out, meta)


def pitch(x, rate):
    """Median F0 (Hz) of the voiced frames: autocorrelation, 40 ms frames."""
    import numpy as np
    if rate != 16000:
        idx = np.arange(0, len(x), rate / 16000)
        x = np.interp(idx, np.arange(len(x)), x)
        rate = 16000
    n, hop = 640, 160
    frames = [x[i:i + n] for i in range(0, len(x) - n, hop)]
    rms = np.array([np.sqrt(np.mean(f ** 2)) for f in frames]) if frames else np.array([])
    if not len(rms):
        return 0.0
    f0s = []
    lo, hi = int(rate / 400), int(rate / 60)
    for f, r in zip(frames, rms):
        if r < 0.15 * rms.max():
            continue
        f = f - f.mean()
        ac = np.correlate(f, f, "full")[n - 1:]
        if ac[0] <= 0:
            continue
        ac = ac / ac[0]
        lag = lo + int(np.argmax(ac[lo:hi]))
        if ac[lag] > 0.5:
            f0s.append(rate / lag)
    return float(np.median(f0s)) if f0s else 0.0


def _norm(s):
    s = unicodedata.normalize("NFC", s).lower()
    return "".join(c for c in s if unicodedata.category(c)[0] in "LMN")


def cer(hyp, ref):
    a, b = _norm(hyp), _norm(ref)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1] / max(1, len(b))


def score(args):
    from faster_whisper import WhisperModel
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "server"))
    import stack_config
    wm = stack_config.load_models()[0]["whisper"]
    asr = WhisperModel(wm["model"], device="cuda", compute_type="float16", revision=wm["revision"] or None)
    meta = _meta(args.out)
    rows = {}
    for key, m in sorted(meta.items()):
        if key.startswith("_"):
            continue
        lang = key.split("/")[0]
        x, rate = read_wav(os.path.join(args.out, key))
        import numpy as np
        segs, _ = asr.transcribe(x if rate == 16000 else np.interp(np.arange(0, len(x), rate / 16000),
                                                                    np.arange(len(x)), x).astype(np.float32),
                                 language=lang, beam_size=5)
        heard = " ".join(s.text for s in segs).strip()
        m.update(heard=heard, cer=cer(heard, m["text"]), f0=pitch(x, rate))
        rows[key] = m
    _save_meta(args.out, meta)
    picks = {}
    for lang in sorted({k.split("/")[0] for k in rows}):
        print(f"\n== {lang}")
        best = None
        for cand in DESIGNS:
            ref = rows.get(f"{lang}/cand_{cand}.wav")
            if not ref:
                continue
            for eng in ("vox", "cb"):
                clones = [rows[k] for k in rows if k.startswith(f"{lang}/{eng}_{cand}_")]
                if not clones:
                    continue
                f0 = [c["f0"] for c in clones]
                stable = ref["f0"] > 0 and all(
                    abs(v - ref["f0"]) / ref["f0"] <= 0.25 and (v >= 165) == (ref["f0"] >= 165) for v in f0)
                mean_cer = sum(c["cer"] for c in clones) / len(clones)
                rtf = sum(c["gen_s"] for c in clones) / max(1e-6, sum(c["audio_s"] for c in clones))
                print(f"  {cand} {eng:3} ref f0 {ref['f0']:5.0f} Hz cer {ref['cer']:5.1%} | clones f0 "
                      f"{' '.join(f'{v:4.0f}' for v in f0)} {'stable' if stable else 'UNSTABLE'} "
                      f"cer {mean_cer:5.1%} rtf {rtf:.2f}")
                if eng == "vox" and stable and (best is None or mean_cer < best[1]):
                    best = (cand, mean_cer)
        picks[lang] = best[0] if best else None
        print(f"  pick: {picks[lang]}")
    if "_chatterbox" in meta:
        print(f"\nchatterbox: {meta['_chatterbox']}")
    json.dump(picks, open(os.path.join(args.out, "picks.json"), "w"))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("step", choices=("gen", "chatterbox", "score"))
    ap.add_argument("--out", required=True)
    ap.add_argument("--langs", default=",".join(SENTENCES))
    ap.add_argument("--repo", default=None, help="default: languages.toml [models.voxcpm]")
    ap.add_argument("--revision", default=None, help="default: languages.toml [models.voxcpm]")
    # The Chatterbox Multilingual trial of 2026-09-29 (docs/licences.md §11); not a stack engine.
    ap.add_argument("--cb-revision", default="5bb1f6ee58e50c3b8d408bc82a6d3740c2db6e18")
    a = ap.parse_args()
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "server"))
    import stack_config
    _m = stack_config.load_models()[0]
    a.repo = a.repo or _m["voxcpm"]["repo"]
    a.revision = a.revision or _m["voxcpm"]["revision"]
    a.langs = [l for l in a.langs.split(",") if l]
    os.makedirs(a.out, exist_ok=True)
    {"gen": gen, "chatterbox": chatterbox, "score": score}[a.step](a)
